### ISSUE TITLE
小米平板6S PRO兼容性反馈

### ISSUE THREAD

**Issue by devhaozi** [CwithW/MiuiPadMeta#6]
环境：澎湃OS 1.0.7 KSU 11807 LSP 1.9.2(7058)

禁用Alt-Tab正常
恢复WIN键不生效

LSP 日志输出：
```
[ 2024-05-18T03:04:08.073     1000:  2808:  2808 I/LSPosed-Bridge  ] MiuiPadMeta: Using Android 12+ hooks.
[ 2024-05-18T03:04:08.075     1000:  2808:  2808 I/LSPosed-Bridge  ] MiuiPadMeta: MIUIHotkeyHooksAndroid12 failed!
[ 2024-05-18T03:04:08.075     1000:  2808:  2808 E/LSPosed-Bridge  ] java.lang.ClassNotFoundException: Didn't find class "com.android.server.policy.MiuiKeyShortcutManager" on path: DexPathList[[zip file "/system/framework/com.android.location.provider.jar", zip file "/system/framework/services.jar", zip file "/system_ext/framework/miui-services.jar", zip file "/system_ext/framework/apprecovery.proinstaller.jar", zip file "/apex/com.android.adservices/javalib/service-adservices.jar", zip file "/apex/com.android.adservices/javalib/service-sdksandbox.jar", zip file "/apex/com.android.appsearch/javalib/service-appsearch.jar", zip file "/apex/com.android.art/javalib/service-art.jar", zip file "/apex/com.android.configinfrastructure/javalib/service-configinfrastructure.jar", zip file "/apex/com.android.healthfitness/javalib/service-healthfitness.jar", zip file "/apex/com.android.media/javalib/service-media-s.jar", zip file "/apex/com.android.ondevicepersonalization/javalib/service-ondevicepersonalization.jar", zip file "/apex/com.android.permission/javalib/service-permission.jar", zip file "/apex/com.android.rkpd/javalib/service-rkp.jar", zip file "/system_ext/framework/miui-services.autoui.jar", zip file "/system_ext/framework/miui-services-pointer-pad.jar", zip file "/system_ext/framework/miuix.jar", zip file "/system_ext/framework/miui-embedding-window.jar"],nativeLibraryDirectories=[/system/lib64, /system_ext/lib64, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at b.b.e(:5)
	at k.d.a(:2)
	at pub.chara.miuipadmeta.MainHook.a(Unknown Source:15)
	at pub.chara.miuipadmeta.MainHook.handleLoadPackage(:5)
	at Ae.n.h.XL.ybtHp.WnDuHU.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at Ae.n.h.XL.ybtHp.WnDuHU.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at Ae.n.h.XL.ybtHp.WnDuHU.callbacks.XCallback.callAll(Unknown Source:26)
	at H0.a(Unknown Source:30)
	at java.lang.reflect.Method.invoke(Native Method)
	at J.callback(Unknown Source:123)
	at LSPHooker_.startBootstrapServices(Unknown Source:11)
	at com.android.server.SystemServer.run(SystemServer.java:1006)
	at com.android.server.SystemServer.main(SystemServer.java:724)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:991)
```

**Comment by devhaozi** [comment]
我可以协助帮提取文件和测试，如果作者有适配需要的话。

**Comment by CwithW** [comment]
should be fixed
